spring:
  datasource:
    url: jdbc:mysql://118.25.0.88:3306/test
    username: zsy_mysql
    password: ZSY123abc$%^
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  profiles:
    active: dev
