spring:
  datasource:
    url: jdbc:mysql://118.25.0.88:3306/test
    username: zsy_mysql
    password: ZSY123abc$%^
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8

